// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AllRostersController from "./all_rosters_controller"
import SingleRosterController from "./single_roster_controller"
application.register("all-rosters", AllRostersController)
application.register("single-roster", SingleRosterController)
