require:
  - standard
  - rubocop-rails

inherit_gem:
  standard: config/base.yml

Bundler/OrderedGems:
  Enabled: true

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/migrate/*.*'
    - 'db/schema.rb'
    - 'bin/*'
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/KeywordParametersOrder:
  Exclude:
    - 'app/models/concerns/cacheable.rb'

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'app/controllers/application_controller.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/lib/*_queries.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/lib/*_queries.rb'
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'

Metrics/AbcSize:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/lib/model_indexer.rb'

Rails/SquishedSQLHeredocs:
  Enabled: false
Rails/Pluck:
  Enabled: false
Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api_controller.rb'
    - 'app/controllers/reports_controller.rb'

Rails/RootPublicPath:
  Enabled: false
